# Generated by Django 4.0.5 on 2022-06-16 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('miFamilia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrantes',
            name='fechaNacimiento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
